11-Sep-2023 18:06:54 - ERROR - DB_actions.py - 95 - Eroare la introducerea in datelor in baza de date. Query-ul a fost scris gresit. 
 syntax error at or near ")"
LINE 2: ...                                  values ('', '', '', '', );
                                                                     ^

11-Sep-2023 20:04:56 - INFO - DB_actions.py - 144 - User  a accesat baza de date
                pentru a modifica stockul din depozit pentru 0102C-13256, acesta fiind acum 1.
11-Sep-2023 20:05:04 - INFO - DB_actions.py - 144 - User  a accesat baza de date
                pentru a modifica stockul din depozit pentru 0102C-13256, acesta fiind acum 1.
11-Sep-2023 20:05:12 - INFO - DB_actions.py - 144 - User  a accesat baza de date
                pentru a modifica stockul din depozit pentru 0102C-13256, acesta fiind acum 2.
11-Sep-2023 20:08:34 - ERROR - DB_actions.py - 161 - Eroare la introducerea in datelor in baza de date. Query-ul a fost scris gresit. 
 unterminated quoted identifier at or near "" = '0102C-14003';"
LINE 3: ...                                WHERE "Part_number" = '0102C...
                                                             ^

11-Sep-2023 20:10:13 - INFO - DB_actions.py - 153 - User  a accesat baza de date
                pentru a modifica stockul din depozit pentru 0102C-14003, acesta fiind acum (9,).
11-Sep-2023 20:10:40 - INFO - DB_actions.py - 153 - User  a accesat baza de date
                pentru a modifica stockul din depozit pentru 0102C-14003, acesta fiind acum 10.
11-Sep-2023 20:12:58 - ERROR - DB_actions.py - 95 - Eroare la introducerea in datelor in baza de date. Query-ul a fost scris gresit. 
 syntax error at or near ")"
LINE 2: ...                       values ('0102C-14003', '', '', '', );
                                                                     ^

13-Sep-2023 20:03:01 - ERROR - DB_actions.py - 56 - Eroare la introducerea datelor in baza de date: invalid input syntax for type integer: ""
LINE 3:                             "KW" = '',
                                           ^

16-Sep-2023 12:59:23 - INFO - DB_actions.py - 46 - User  a accesat baza de date pentru a modifica datele masinii: B24AEN, WF04XXWPD46R72874.
16-Sep-2023 13:00:41 - INFO - DB_actions.py - 46 - User  a accesat baza de date pentru a modifica datele masinii: B51TSV, WNUSFJ12U3N445556.
16-Sep-2023 14:11:30 - INFO - login_sequence.py - 50 - Utilizatorul necula77 s-a logat cu succes.
16-Sep-2023 14:11:51 - INFO - login_sequence.py - 50 - Utilizatorul necula77 s-a logat cu succes.
16-Sep-2023 14:12:02 - INFO - login_sequence.py - 50 - Utilizatorul necula77 s-a logat cu succes.
16-Sep-2023 14:12:14 - INFO - login_sequence.py - 50 - Utilizatorul necula77 s-a logat cu succes.
16-Sep-2023 14:12:23 - INFO - login_sequence.py - 50 - Utilizatorul necula77 s-a logat cu succes.
16-Sep-2023 14:12:34 - INFO - login_sequence.py - 50 - Utilizatorul necula77 s-a logat cu succes.
16-Sep-2023 14:13:15 - INFO - login_sequence.py - 50 - Utilizatorul sefu s-a logat cu succes.
16-Sep-2023 18:38:23 - ERROR - login_sequence.py - 85 - Eroare la inregistrare: column "authorization_level" of relation "LOGIN_INFO" does not exist
LINE 2:                                 "function", authorization_le...
                                                    ^

16-Sep-2023 18:39:13 - ERROR - login_sequence.py - 85 - Eroare la inregistrare: function gen_salt(unknown) does not exist
LINE 3: ...         VALUES('Mircea', 'Cioaca', crypt('sefu', gen_salt('...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

16-Sep-2023 18:39:52 - ERROR - login_sequence.py - 85 - Eroare la inregistrare: syntax error at or near ";"
LINE 4:                                  'gsdv', CURRENT_DATE);
                                                              ^

16-Sep-2023 18:40:27 - ERROR - login_sequence.py - 85 - Eroare la inregistrare: syntax error at or near ";"
LINE 4:                                  'fdscf', CURRENT_DATE;
                                                              ^

16-Sep-2023 18:40:46 - ERROR - login_sequence.py - 85 - Eroare la inregistrare: new row for relation "LOGIN_INFO" violates check constraint "LOGIN_INFO_function_check"
DETAIL:  Failing row contains (3, Mircea, sadfm, sefu, 123, dmskf, 2023-09-16).

16-Sep-2023 18:41:39 - INFO - login_sequence.py - 76 - User: sefu a fost adaugat in baza de date, NUME: fas PRENUME: Mircea.
16-Sep-2023 18:42:08 - INFO - login_sequence.py - 53 - Utilizatorul sefu s-a logat cu succes.
16-Sep-2023 18:43:42 - ERROR - login_sequence.py - 85 - Eroare la inregistrare: new row for relation "LOGIN_INFO" violates check constraint "LOGIN_INFO_function_check"
DETAIL:  Failing row contains (5, , , , , , 2023-09-16).

16-Sep-2023 18:44:29 - ERROR - login_sequence.py - 85 - Eroare la inregistrare: new row for relation "LOGIN_INFO" violates check constraint "LOGIN_INFO_function_check"
DETAIL:  Failing row contains (6, , , , , , 2023-09-16).

16-Sep-2023 18:44:44 - INFO - login_sequence.py - 76 - User: diosf a fost adaugat in baza de date, NUME: dskmfo PRENUME: asmkd.
16-Sep-2023 18:44:45 - ERROR - login_sequence.py - 80 - Username-ul: diosf, exista deja, va rugam sa alegeti altul.
16-Sep-2023 18:44:46 - ERROR - login_sequence.py - 80 - Username-ul: diosf, exista deja, va rugam sa alegeti altul.
16-Sep-2023 18:44:47 - ERROR - login_sequence.py - 80 - Username-ul: diosf, exista deja, va rugam sa alegeti altul.
16-Sep-2023 18:44:47 - ERROR - login_sequence.py - 80 - Username-ul: diosf, exista deja, va rugam sa alegeti altul.
16-Sep-2023 18:44:47 - ERROR - login_sequence.py - 80 - Username-ul: diosf, exista deja, va rugam sa alegeti altul.
16-Sep-2023 18:44:48 - ERROR - login_sequence.py - 80 - Username-ul: diosf, exista deja, va rugam sa alegeti altul.
16-Sep-2023 18:44:48 - ERROR - login_sequence.py - 80 - Username-ul: diosf, exista deja, va rugam sa alegeti altul.
16-Sep-2023 18:44:48 - ERROR - login_sequence.py - 80 - Username-ul: diosf, exista deja, va rugam sa alegeti altul.
16-Sep-2023 18:44:48 - ERROR - login_sequence.py - 80 - Username-ul: diosf, exista deja, va rugam sa alegeti altul.
16-Sep-2023 18:44:48 - ERROR - login_sequence.py - 80 - Username-ul: diosf, exista deja, va rugam sa alegeti altul.
16-Sep-2023 18:44:49 - ERROR - login_sequence.py - 80 - Username-ul: diosf, exista deja, va rugam sa alegeti altul.
16-Sep-2023 18:44:49 - ERROR - login_sequence.py - 80 - Username-ul: diosf, exista deja, va rugam sa alegeti altul.
16-Sep-2023 18:45:12 - INFO - login_sequence.py - 76 - User: noknfdsa a fost adaugat in baza de date, NUME: kmidofs PRENUME: afskma.
